name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install emacs-nox
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: '26.2.4'
          rebar3-version: '3.23.0'
      - name: erlang-formatter
        run: |
          rebar3 as check fmt
          status="$(git status --untracked-file=no --porcelain)"
          if [ ! -z "$status" ]; \
          then \
             echo "Error: Please format the following files (e.g. run 'rebar3 as check fmt')"; \
             echo "$status"; \
             exit 1; \
          fi

  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp-version: '27.0-rc3'
          - otp-version: '26.2.4'
          - otp-version: '25.3.2.11'
          - otp-version: '24.3.4.17'
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: ${{ matrix.otp-version }}
          rebar3-version: '3.23.0'
      - name: Install redis-cli
        # Required by ct
        run: |
          sudo apt update
          sudo apt install redis-server
      - name: Compile
        run: rebar3 compile
      - name: Run eunit tests
        run: |
          docker run -d --net=host redis
          rebar3 eunit
      - name: Run common tests
        run: rebar3 ct
      - name: Run dialyzer
        run: rebar3 as test dialyzer
