name: DB compatibility testing

on: [push, pull_request]

permissions:
  contents: read

jobs:
  valkey:
    name: Valkey ${{ matrix.valkey-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - valkey-version: 7.2.5
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install redis-cli required by common tests
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: redis-server
          version: 1.0
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: '26.2.4'
          rebar3-version: '3.23.0'
      - name: Build and run common tests
        env:
          REDIS_DOCKER_IMAGE: valkey/valkey:${{ matrix.valkey-version }}
        run: |
          rebar3 ct

  redis:
    name: Redis ${{ matrix.redis-version }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - redis-version: 7.2.4 # Last open source release
          - redis-version: 7.0.15
          - redis-version: 6.2.14
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install redis-cli required by common tests
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: redis-server
          version: 1.0
      - name: Install Erlang/OTP
        uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: '26.2.4'
          rebar3-version: '3.23.0'
      - name: Build and run common tests
        env:
          REDIS_DOCKER_IMAGE: redis:${{ matrix.redis-version }}
        run: |
          rebar3 ct
